service: campfire

image: smallbets/campfire

servers:
  web:
    - 5.161.17.168

proxy:
  ssl: true
  host: chat.smallbets.com
  app_port: 3000

registry:
  username: dvassallo

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DISABLE_SSL: "true"
    RAILS_ENV: "production"

  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
    - GUMROAD_ACCESS_TOKEN
    - GUMROAD_ON
    - GUMROAD_PRODUCT_ID
    - WEBHOOK_SECRET

volumes:
  - "/disk/campfire/:/rails/storage/"
