service: campfire

image: smallbets/campfire

servers:
  web:
    - <%= ENV.fetch("SERVER_IP") %>

proxy:
  ssl: true
  host: <%= ENV.fetch("PROXY_HOST") %>
  app_port: 3000

registry:
  username: <%= ENV.fetch("REGISTRY_USERNAME") %>

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DISABLE_SSL: "true"
    RAILS_ENV: "production"

  secret:
    - APP_VERSION
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
    - GUMROAD_ACCESS_TOKEN
    - GUMROAD_ON
    - GUMROAD_PRODUCT_IDS
    - WEBHOOK_SECRET

volumes:
  - "/disk/campfire/:/rails/storage/"
